---
- name: Execute task on Master
  shell: "{{ item }}"
  with_items:
    - sudo -Hiu postgres psql -c "create user replication REPLICATION LOGIN ENCRYPTED PASSWORD 'hoanm';"
    #- sudo -u postgres ALTER ROLE replication CONNECTION LIMIT -1;
    - echo -e "listen_addresses = 'localhost,MYIP1'\nwal_level = replica\nmax_wal_senders = 10\nwal_keep_segments = 64" >> /etc/postgresql/12/main/postgresql.conf
    - echo "host    replication     replication     MYIP2/0       trust" >> /etc/postgresql/12/main/pg_hba.conf
    - echo "host    replication     replication     MYIP3/0       trust" >> /etc/postgresql/12/main/pg_hba.conf
  when:
    - inventory_hostname == groups['postgre_cluster'][0]

- name: Execute task on Slave1
  shell: "{{ item }}"                       
  with_items:
    - systemctl stop postgresql
    - echo -e "listen_addresses = 'localhost,MYIP2'\nwal_level = replica\nmax_wal_senders = 10\nwal_keep_segments = 64\nhot_standby = on" >> /etc/postgresql/12/main/postgresql.conf
    - echo "host    replication     replication     MYIP1/0       trust" >> /etc/postgresql/12/main/pg_hba.conf 
    - rm -rf /var/lib/postgresql/12/main/*
    - sudo -Hiu postgres pg_basebackup -h MYIP1 -U replication -p 5432 -D /var/lib/postgresql/12/main/  -Fp -Xs -P -R
    - systemctl start postgresql
  when:
    - inventory_hostname == groups['postgre_cluster'][1]

- name: Execute task on Slave2
  shell: "{{ item }}"
  with_items:
    - systemctl stop postgresql
    - echo -e "listen_addresses = 'localhost,MYIP3'\nwal_level = replica\nmax_wal_senders = 10\nwal_keep_segments = 64\nhot_standby = on" >> /etc/postgresql/12/main/postgresql.conf
    - echo "host    replication     replication     MYIP1/0       trust" >> /etc/postgresql/12/main/pg_hba.conf
    - rm -rf /var/lib/postgresql/12/main/*
    - sudo -Hiu postgres pg_basebackup -h MYIP1 -U replication -p 5432 -D /var/lib/postgresql/12/main/  -Fp -Xs -P -R
    - systemctl start postgresql
  when:
    - inventory_hostname == groups['postgre_cluster'][2]
