---
- name: Install software-properties-common
  become: yes
  become_user: root
  apt: name={{ item }} state=present update_cache=yes
  loop:
    - software-properties-common

- name: Add Postgre keys
  become: yes
  become_user: root
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgre repo
  become: yes
  become_user: root  
  template: src=sources.list.d/pgdg.list.j2 dest=/etc/apt/sources.list.d/pgdg.list
    owner=root group=root mode=0644
